In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [25]:
from sklearn.datasets import load_wine

In [27]:
wine=load_wine()

In [39]:
X=pd.DataFrame(data=wine.data,columns=wine.feature_names)
y=wine.target

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [45]:
reg=LogisticRegression()
tree=DecisionTreeClassifier()
svm=SVC()
rfc=RandomForestClassifier()
kne=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(y))))

In [47]:
reg=reg.fit(X_train,y_train)
tree=tree.fit(X_train,y_train)
svm=svm.fit(X_train,y_train)
rfc=rfc.fit(X_train,y_train)
kne=kne.fit(X_train,y_train)

/home/chaudharyshubham/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [48]:
preg=reg.predict(X_test)
ptree=tree.predict(X_test)
psvm=svm.predict(X_test)
prfc=rfc.predict(X_test)
pkne=kne.predict(X_test)

In [49]:
from sklearn.metrics import classification_report,confusion_matrix

In [50]:
print('preg') 
print(classification_report(y_test,preg))
print(confusion_matrix(y_test,preg))
print('ptree') 
print(classification_report(y_test,ptree))
print(confusion_matrix(y_test,ptree))
print('psvm') 
print(classification_report(y_test,psvm))
print(confusion_matrix(y_test,psvm))
print('prfc') 
print(classification_report(y_test,prfc))
print(confusion_matrix(y_test,prfc))
print('pkne') 
print(classification_report(y_test,pkne))
print(confusion_matrix(y_test,pkne))

preg
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        14
           1       0.93      0.88      0.90        16
           2       0.86      1.00      0.92         6

    accuracy                           0.92        36
   macro avg       0.91      0.93      0.92        36
weighted avg       0.92      0.92      0.92        36

[[13  1  0]
 [ 1 14  1]
 [ 0  0  6]]
ptree
              precision    recall  f1-score   support

           0       0.93      1.00      0.97        14
           1       1.00      0.94      0.97        16
           2       1.00      1.00      1.00         6

    accuracy                           0.97        36
   macro avg       0.98      0.98      0.98        36
weighted avg       0.97      0.97      0.97        36

[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]
psvm
              precision    recall  f1-score   support

           0       1.00      0.93      0.96        14
           1       0.80      0.75      

In [52]:
print(reg.score(X_test,y_test) )
print(tree.score(X_test,y_test)) 
print(svm.score(X_test,y_test) )
print(rfc.score(X_test,y_test)) 
print(kne.score(X_test,y_test) )
  

0.9166666666666666
0.9722222222222222
0.7777777777777778
0.9722222222222222
0.75
